name: HeroVender
version: ${project.version}
main: com.heroslender.herovender.HeroVender
api-version: 1.13
authors: [Heroslender]
depend: [Vault]
softdepend: [HeroStackDrops, AutoPickup]
description: Plugin de /vender com bolsa de valores
website: www.heroslender.cf/plugins/HeroVender
